"""
llm_router.py
-------------
Block 5 — LLM Routing.

Sends scrubbed attack narratives + the full set of detected anomalous events
to an LLM and returns a comprehensive incident analysis in a single call
per campaign.

The model sees the full scrubbed narrative (all sensitive identifiers
replaced with typed placeholders by Block 4) plus every signature rule
hit grouped by rule. Five sections are returned:

  risk_assessment      — numerical risk score + confidence + justification
  executive_summary    — title + one-paragraph plain-English summary
  attack_timeline      — chronological narrative beats with timestamps
  remediation          — severity_explanation + immediate / short / long actions
  anomaly_explanation  — why the detectors fired in plain English

The final report then assembles:
  executive_summary    — exec-readable headline
  attack_timeline      — story of the attack
  risk_assessment      — numerical risk verdict
  remediation          — the actionable fix
  key_evidence         — top 5 plain-English signals (re-identified)
  anomaly_explanation  — LLM's analysis
  detected_anomalies   — ALL rule-hit events with score / MITRE / what_it_means
  iocs                 — attacker IPs, techniques, affected assets

Compliance / HIPAA / breach notification — REMOVED. This system stays
focused on detection + remediation. Compliance is a separate workflow.
"""
from __future__ import annotations

import json
import os
import re
import time
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from ... import llm, config          # furix's in-house Gemma client + config
from ..scrub.dal_scrubber import DALScrubber

# RULE_DESCRIPTION / RULE_TACTIC_OVERRIDE / load_anomaly_store come from the
# anomaly store (Module 8), which may not be ported yet. Degrade gracefully:
# without it the prompt's per-rule evidence block uses the event's own MITRE
# fields and a generic description, and process_campaigns runs with an empty
# rule-hit-event set. Picks up the real tables once Module 8 lands.
try:
    from ..detect.anomaly_store import (
        RULE_DESCRIPTION, RULE_TACTIC_OVERRIDE, load_anomaly_store,
    )
except Exception:
    RULE_DESCRIPTION: Dict[str, str] = {}
    RULE_TACTIC_OVERRIDE: Dict[str, tuple] = {}

    def load_anomaly_store(path):   # noqa: D401 — fallback stub
        return None


# =============================================================================
#  Configuration
# =============================================================================

# The report is generated by the in-house Gemma via furix's llm.complete_json
# (re-pointed from the source engine's OpenRouter call). Model + endpoint +
# temperature come from furix config; we only set the larger token budget a
# full campaign report needs (furix's default 1600 would truncate it).
MAX_TOKENS      = 3000

# Only process campaigns at or above this confidence. Single source of truth is
# the correlator (the verifier flagged this constant was duplicated).
from ..correlate import MIN_LLM_CONFIDENCE

# Five required sections (compliance removed)
REQUIRED_SECTIONS = [
    "risk_assessment",
    "executive_summary",
    "attack_timeline",
    "remediation",
    "anomaly_explanation",
]

# Response schema injected into the prompt
_RESPONSE_SCHEMA = """{
  "risk_assessment": {
    "score": <integer 0-100>,
    "severity": "<CRITICAL|HIGH|MEDIUM|LOW>",
    "confidence": <float 0.0-1.0>,
    "justification": "<2-3 sentences explaining the score>"
  },
  "executive_summary": {
    "title": "<concise incident title, ≤12 words>",
    "one_paragraph": "<3-4 sentence executive summary suitable for C-suite>",
    "attack_vector": "<single sentence: how the attacker got in>",
    "blast_radius": "<single sentence: what was exposed or at risk>"
  },
  "attack_timeline": [
    {
      "time": "<HH:MM>",
      "stage": "<MITRE tactic name>",
      "event": "<single sentence describing what happened at this beat>",
      "entity": "<the placeholder entity involved, e.g. EXEC_USER_1>"
    }
  ],
  "remediation": {
    "severity_explanation": "<why this severity level — reference specific evidence>",
    "immediate_actions": ["<action to take within 1 hour, specific to evidence>"],
    "short_term_actions": ["<action to take within 24 hours>"],
    "long_term_actions":  ["<strategic control improvement for 30-day horizon>"]
  },
  "anomaly_explanation": {
    "summary": "<1-2 sentences: overall reason the detectors fired>",
    "key_indicators": [
      {
        "indicator": "<rule or detector name>",
        "plain_english": "<non-technical explanation>",
        "why_suspicious": "<context-specific reason it is a red flag>",
        "mitre_context": "<technique ID and tactic name as given in the prompt — do not change the tactic>"
      }
    ]
  }
}"""


# =============================================================================
#  Helpers — entity breakdown, formatting
# =============================================================================

def _count_by_prefix(entities: List[dict]) -> dict:
    """Count entities by their placeholder category prefix."""
    counts: Dict[str, int] = {}
    for ent in entities:
        key = ent.get("entity_key") or ent.get("entity", "")
        match = re.match(r'^([A-Z]+(?:_[A-Z]+)*)_\d+$', key)
        if match:
            category = match.group(1)
        else:
            category = (ent.get("entity_type") or ent.get("type", "UNKNOWN")).upper()
        counts[category] = counts.get(category, 0) + 1
    return counts


def _format_stage(stage: dict) -> str:
    """Compact one-stage block for the high-level timeline section."""
    s    = stage.get("stage", "?")
    name = stage.get("name", "Unknown")
    ts   = stage.get("first_seen", "")[:16] if stage.get("first_seen") else "?"
    ents = [e.get("entity", e.get("entity_key", "?"))
            for e in stage.get("entities", [])]
    ev   = stage.get("evidence", [])

    ent_str = ", ".join(ents[:4]) + (" (+more)" if len(ents) > 4 else "")
    ev_str  = ", ".join(ev[:4])  + (" (+more)" if len(ev)  > 4 else "")

    lines = [f"  Stage {s:>2} — {name:<22} [{ts}]"]
    if ent_str:
        lines.append(f"    Entities  : {ent_str}")
    if ev_str:
        lines.append(f"    Evidence  : {ev_str}")
    return "\n".join(lines)


def _format_rule_evidence_grouped(
    rule_hit_events:   List[dict],
    placeholder_map:   Dict[str, str],
    limit_per_rule:    int = 6,
) -> str:
    """
    Format ALL signature_rules hits, grouped by rule name.

    For each rule:
      - 1 header line with rule, count, MITRE tactic context, description
      - up to limit_per_rule instances with time + entity + IPs

    Entity / IP values are scrubbed to placeholders for the prompt
    (since the LLM never sees raw identifiers).
    """
    def _scrub(value: str) -> str:
        return placeholder_map.get(value, value) if value else ""

    by_rule: Dict[str, List[dict]] = defaultdict(list)
    for ev in rule_hit_events:
        for rule in ev.get("all_rules_fired", []):
            by_rule[rule].append(ev)

    if not by_rule:
        return "  (no signature rules fired)"

    # Order rules by kill chain stage, then by count
    def _rule_sort_key(rule_name: str):
        override = RULE_TACTIC_OVERRIDE.get(rule_name)
        stage    = override[2] if override else 99
        return (stage, -len(by_rule[rule_name]))

    blocks = []
    for rule in sorted(by_rule, key=_rule_sort_key):
        events     = by_rule[rule]
        description = RULE_DESCRIPTION.get(rule, "Anomalous behaviour")
        override   = RULE_TACTIC_OVERRIDE.get(rule)
        if override:
            tid, tactic, stage = override
            mitre_label = f"{tid} — {tactic} (Stage {stage})"
        else:
            ev0 = events[0]
            mitre_label = (f"{ev0.get('mitre_technique_id','?')} — "
                           f"{ev0.get('mitre_tactic','?')} "
                           f"(Stage {ev0.get('kill_chain_stage','?')})")

        # Confidence band — use the max across instances
        max_conf = max(float(e.get("rule_confidence", 0)) for e in events)

        header = (
            f"\n  RULE: {rule}  ({len(events)} event{'s' if len(events) != 1 else ''})  "
            f"confidence={max_conf:.2f}\n"
            f"    MITRE        : {mitre_label}\n"
            f"    Description  : {description}"
        )

        instance_lines = []
        for ev in events[:limit_per_rule]:
            ts     = ev.get("timestamp", "")[11:19]  # HH:MM:SS
            raw_entity = ev.get("entity", "")
            # Mark explicitly when no user is associated with the event so
            # the LLM does NOT hallucinate a plausible name from context.
            # Common case: firewall/network events without authenticated user.
            entity = _scrub(raw_entity) if raw_entity else "<no-user-on-event>"
            sip    = _scrub(ev.get("source_ip", ""))
            dip    = _scrub(ev.get("destination_ip", ""))
            dport  = ev.get("destination_port", 0) or ""

            parts = [f"{ts}  entity={entity}"]
            if sip:
                parts.append(f"src={sip}")
            if dip:
                ipport = f"dst={dip}" + (f":{dport}" if dport else "")
                parts.append(ipport)
            instance_lines.append("      " + "  ".join(parts))

        if len(events) > limit_per_rule:
            instance_lines.append(f"      ... (+{len(events) - limit_per_rule} more)")

        block = header + "\n    Instances    :\n" + "\n".join(instance_lines)
        blocks.append(block)

    return "\n".join(blocks)


def _build_placeholder_map(
    narrative:        dict,
    mapping_entry:    dict,
    rule_hit_events:  Optional[List[dict]] = None,
) -> Dict[str, str]:
    """
    Build a {original_value → placeholder} map by inverting the reverse map.
    Used to scrub raw values from anomaly_events.json before they enter the prompt.

    Augments the existing mapping with any new tokens found in rule_hit_events
    (destination IPs, additional usernames, etc.) that weren't in the original
    campaign IOCs. New placeholders are added to mapping_entry's reverse map
    so re-identification still works after the LLM responds.
    """
    from ..scrub.dal_scrubber import _classify

    reverse  = mapping_entry.get("reverse", {}) if mapping_entry else {}
    mapping  = mapping_entry.get("mapping", {}) if mapping_entry else {}
    fwd_map  = {orig: ph for ph, orig in reverse.items()}

    # Find max counter for each category so new placeholders don't collide
    cat_counters: Dict[str, int] = defaultdict(int)
    for ph in reverse.keys():
        match = re.match(r'^([A-Z]+(?:_[A-Z]+)*)_(\d+)$', ph)
        if match:
            cat = match.group(1)
            n   = int(match.group(2))
            if n > cat_counters[cat]:
                cat_counters[cat] = n

    if not rule_hit_events:
        return fwd_map

    # Attacker IPs (for ATTACKER_IP classification) — reuse the narrative's set
    iocs = narrative.get("llm_context", {}).get("structured_data", {}).get("iocs", {})
    raw_iocs = narrative.get("iocs", iocs)
    attacker_ips = set(raw_iocs.get("external_ips", []))
    # Also include any external IP already classified as ATTACKER_IP in existing map
    for orig, ph in fwd_map.items():
        if ph.startswith("ATTACKER_IP_"):
            attacker_ips.add(orig)

    # Scan rule_hit_events for tokens needing scrubbing
    new_tokens: List[str] = []
    for ev in rule_hit_events:
        for field in ("entity", "source_ip", "destination_ip"):
            val = ev.get(field, "")
            if val and isinstance(val, str) and len(val) >= 2:
                if val not in fwd_map:
                    new_tokens.append(val)

    # Assign placeholders for new tokens
    seen = set()
    for token in new_tokens:
        if token in seen or token in fwd_map:
            continue
        seen.add(token)
        category = _classify(token, attacker_ips)
        cat_counters[category] += 1
        placeholder = f"{category}_{cat_counters[category]}"
        fwd_map[token] = placeholder
        # Update mapping_entry in-place so re-identification can restore later
        if mapping_entry is not None:
            mapping_entry.setdefault("reverse", {})[placeholder] = token
            mapping_entry.setdefault("mapping", {})[token]        = placeholder

    return fwd_map


# =============================================================================
#  Prompt builder
# =============================================================================

def build_prompt_messages(
    narrative:        dict,
    rule_hit_events:  List[dict],
    placeholder_map:  Dict[str, str],
) -> List[dict]:
    """
    Build the system + user messages for one scrubbed narrative.
    Now includes ALL signature_rules hits grouped by rule, plus
    explicit tactic context for each rule.
    """
    sd       = narrative.get("llm_context", {}).get("structured_data", {})
    summary  = narrative.get("llm_context", {}).get("narrative_summary", "")

    campaign_id  = narrative.get("campaign_id",          sd.get("campaign_id", "UNKNOWN"))
    severity     = narrative.get("severity",             sd.get("severity", "UNKNOWN"))
    confidence   = narrative.get("confidence",           sd.get("confidence", 0.0))
    duration     = narrative.get("duration_minutes",     sd.get("duration_minutes", 0))
    first_seen   = narrative.get("first_seen",           "")[:19]
    last_seen    = narrative.get("last_seen",            "")[:19]
    completeness = narrative.get("kill_chain_completeness", 0) * 100
    n_stages     = len(narrative.get("kill_chain_coverage", []))
    entry_point  = sd.get("entry_point", narrative.get("entry_point", "unknown"))

    affected     = sd.get("affected_entities", narrative.get("affected_entities", []))
    entity_count = len(affected)
    cat_counts   = _count_by_prefix(affected)
    breakdown    = ", ".join(
        f"{count} {cat.lower().replace('_', ' ')}"
        for cat, count in sorted(cat_counts.items(), key=lambda x: -x[1])
    )

    iocs         = sd.get("iocs", narrative.get("iocs", {}))
    ext_ips      = ", ".join(iocs.get("external_ips", []))     or "none identified"
    techniques   = ", ".join(iocs.get("mitre_techniques", [])) or "see timeline"
    assets       = ", ".join(iocs.get("affected_assets", []))  or "see timeline"
    user_count   = len(iocs.get("affected_users", []))

    stages       = sd.get("attack_timeline", narrative.get("attack_stages", []))
    stages_text  = "\n".join(_format_stage(s) for s in stages) or "  (no stage data)"

    rule_text    = _format_rule_evidence_grouped(
        rule_hit_events, placeholder_map, limit_per_rule=6
    )

    # ── System prompt ──────────────────────────────────────────────
    system_prompt = (
        "You are a senior cybersecurity incident responder with expertise in "
        "threat analysis and SOC operations.\n\n"
        "You are analyzing a correlated attack campaign detected by an automated "
        "multi-layer security system. All sensitive identifiers (usernames, IP addresses, "
        "hostnames) have been replaced with typed placeholders such as EXEC_USER_1, "
        "ATTACKER_IP_2, USER_5, DBA_USER_1. Use these placeholders exactly as given "
        "in your response — do not attempt to guess or reconstruct the real names.\n\n"
        "CRITICAL — MITRE accuracy: When you reference a MITRE technique, use the "
        "tactic exactly as labelled in the prompt for that rule. Do not assign a "
        "different tactic to a technique based on general knowledge. The prompt's "
        "labels are authoritative.\n\n"
        "CRITICAL — Entity accuracy: When an event shows 'entity=<no-user-on-event>', "
        "no user account is associated with that event (firewall, network, or system "
        "event). DO NOT invent or guess a user name for these events. In attack_timeline "
        "and anomaly_explanation, describe them by the source IP placeholder or as "
        "'an internal host' / 'an external IP' — never assign a person name. The same "
        "applies if an entity field is blank: do not fabricate.\n\n"
        "Return ONLY a valid JSON object. No explanation, no markdown, no preamble. "
        "Just the JSON object matching the schema provided."
    )

    # ── User message ───────────────────────────────────────────────
    user_message = f"""## ATTACK CAMPAIGN: {campaign_id}

SEVERITY: {severity} | CONFIDENCE: {confidence:.3f} | DURATION: {duration} minutes
ATTACK WINDOW: {first_seen} → {last_seen}
KILL CHAIN: {n_stages}/14 stages covered ({completeness:.0f}% complete)
ENTRY POINT: {entry_point}
ENTITIES AFFECTED: {entity_count} total ({breakdown})

---
## PRE-ANALYSIS NARRATIVE SUMMARY
{summary}

---
## ATTACK STAGES (kill chain summary)
{stages_text}

---
## ALL RULE-HIT EVIDENCE ({len(rule_hit_events)} events grouped by rule)
{rule_text}

---
## THREAT INDICATORS (IOCs)
External IPs      : {ext_ips}
MITRE Techniques  : {techniques}
Sensitive Assets  : {assets}
User Accounts     : {user_count} individual accounts involved

---
## REQUIRED RESPONSE

Return a JSON object with EXACTLY these five top-level keys:
risk_assessment, executive_summary, attack_timeline, remediation, anomaly_explanation.

For attack_timeline: produce 6-10 timestamped narrative beats in chronological order,
using HH:MM format and the placeholder entity names. Use only stages that are
supported by evidence above. Do not invent events not present in the evidence.

For anomaly_explanation.key_indicators: cover the 5 most significant rule hits,
using the EXACT MITRE tactic labelled in the rule evidence above. Do not substitute.

{_RESPONSE_SCHEMA}"""

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": user_message},
    ]


# =============================================================================
#  API caller
# =============================================================================

# Deterministic stub returned when MOCK_LLM=1 — exercises the scrub→report
# wiring offline. Carries placeholders so re-identification can be verified.
_MOCK_REPORT = {
    "risk_assessment": {
        "score": 88, "severity": "CRITICAL", "confidence": 0.9,
        "justification": "Multi-stage campaign with PHI access involving EXEC_USER_1.",
    },
    "executive_summary": {
        "title": "PHI exfiltration campaign",
        "one_paragraph": "An external actor at ATTACKER_IP_1 correlated activity across "
                         "entities including EXEC_USER_1.",
        "attack_vector": "Phishing of EXEC_USER_1.",
        "blast_radius": "PHI_TABLE_1 exposed.",
    },
    "attack_timeline": [
        {"time": "09:00", "stage": "Collection",
         "event": "Bulk PHI read attributed to EXEC_USER_1.", "entity": "EXEC_USER_1"},
    ],
    "remediation": {
        "severity_explanation": "Confirmed bulk PHI access by a privileged account.",
        "immediate_actions": ["Disable EXEC_USER_1 and revoke active sessions."],
        "short_term_actions": ["Rotate credentials; audit PHI_TABLE_1 access."],
        "long_term_actions": ["Enforce PAM on all PHI database paths."],
    },
    "anomaly_explanation": {
        "summary": "Detectors fired on bulk PHI access far above baseline.",
        "key_indicators": [
            {"indicator": "bulk_phi_query", "plain_english": "Very large PHI table read",
             "why_suspicious": "Row volume far above the user's baseline",
             "mitre_context": "T1213 — Collection"},
        ],
    },
}


def _call_gemma(messages: List[dict]) -> Tuple[dict, dict, str]:
    """Run one campaign report through the in-house Gemma.

    Re-points the source engine's OpenRouter call onto furix's
    ``llm.complete_json``: model / endpoint / temperature come from furix config;
    ``MAX_TOKENS`` overrides furix's smaller default so a full report doesn't
    truncate. ``complete_json`` parses JSON + retries internally and honours
    ``MOCK_LLM``. Returns ``(analysis, api_stats, status)``.
    """
    system = next((m["content"] for m in messages if m.get("role") == "system"), "")
    user   = next((m["content"] for m in messages if m.get("role") == "user"),   "")

    res   = llm.complete_json(system, user, max_tokens=MAX_TOKENS, mock=_MOCK_REPORT)
    stats = {
        "prompt_tokens":     getattr(res, "prompt_tokens", 0),
        "completion_tokens": getattr(res, "completion_tokens", 0),
        "latency_ms":        getattr(res, "latency_ms", 0),
        "json_mode_used":    True,
    }
    if not res:                         # empty result → call failed after retries
        stats["error"] = getattr(res, "error", "empty_response")
        return {}, stats, "failed"
    return dict(res), stats, "success"


# =============================================================================
#  Section validator
# =============================================================================
# (JSON parsing now happens inside furix's llm.complete_json, so the source
# engine's standalone _parse_response is no longer needed.)

def _validate_sections(
    analysis:    dict,
    campaign_id: str,
    model:       str,
) -> dict:
    stub_dict = {
        "_status": "section_unavailable",
        "_reason": "Model did not return this section in its response",
    }

    for section in REQUIRED_SECTIONS:
        if section == "attack_timeline":
            # attack_timeline should be a list, not a dict
            if section not in analysis or not isinstance(analysis[section], list):
                analysis[section] = []
                print(f"[LLMRouter] WARNING: Section '{section}' missing — empty list inserted")
        else:
            if section not in analysis or not isinstance(analysis[section], dict):
                analysis[section] = dict(stub_dict)
                print(f"[LLMRouter] WARNING: Section '{section}' missing — stub inserted")

    return analysis


# =============================================================================
#  Key evidence builder (re-identified, plain English)
# =============================================================================

def _build_key_evidence(
    rule_hit_events: List[dict],
    top_n:           int = 5,
) -> List[dict]:
    """
    Build a curated key_evidence list — top N highest-confidence rule hits
    with one-line plain English. Used AFTER re-identification so values
    in this list are real identifiers, ready for the analyst.
    """
    # Dedup by (rule, entity) so the same rule doesn't dominate
    seen: set = set()
    unique = []
    for ev in sorted(rule_hit_events,
                     key=lambda x: -float(x.get("rule_confidence", 0))):
        rule   = ev.get("primary_rule", "")
        entity = ev.get("entity", "")
        key    = (rule, entity)
        if key not in seen:
            seen.add(key)
            unique.append(ev)
        if len(unique) >= top_n * 2:   # collect 2x to allow rule diversity
            break

    result = []
    for ev in unique[:top_n]:
        result.append({
            "rule":               ev.get("primary_rule"),
            "entity":             ev.get("entity"),
            "source_ip":          ev.get("source_ip"),
            "destination_ip":     ev.get("destination_ip"),
            "what_it_means":      ev.get("what_it_means"),
            "score":              ev.get("rule_score"),
            "confidence":         ev.get("rule_confidence"),
            "mitre_technique_id": ev.get("mitre_technique_id"),
            "mitre_tactic":       ev.get("mitre_tactic"),
            "kill_chain_stage":   ev.get("kill_chain_stage"),
            "timestamp":          ev.get("timestamp"),
        })
    return result


# =============================================================================
#  LLMRouter
# =============================================================================

class LLMRouter:
    """
    Orchestrates the single-call LLM analysis for each scrubbed campaign,
    using the full set of rule-hit events as evidence.

    Usage:
        router = LLMRouter()
        reports = router.process_campaigns(
            scrubbed_narratives,
            anomaly_store_path="results/anomaly_events.json",
            mappings_dir="results/",
            output_dir="results/",
        )
    """

    def __init__(self):
        self._scrubber = DALScrubber()

    # ------------------------------------------------------------------ #
    # Public
    # ------------------------------------------------------------------ #

    def process_campaigns(
        self,
        scrubbed_narratives: List[dict],
        anomaly_store_path:  str = "results/anomaly_events.json",
        mappings_dir:        str = "results/",
        output_dir:          str = "results/",
        *,
        mappings:            Optional[Dict[str, dict]] = None,
        min_confidence:      Optional[float] = None,
    ) -> List[dict]:
        # PII mappings: prefer the in-memory dict the scrubber returned (the
        # decoupled IPC path). Fall back to loading from disk only when not
        # supplied — the on-disk pii_mapping_*.json files are now an audit
        # artifact, not the required scrubber→router channel.
        if mappings is None:
            mappings = self._scrubber.load_mappings(mappings_dir)
        # Confidence gate: defaults to MIN_LLM_CONFIDENCE (0.70). Callers (e.g. the
        # dashboard orchestrator) may pass a lower floor to report smaller campaigns.
        floor = MIN_LLM_CONFIDENCE if min_confidence is None else min_confidence
        anomaly_store = load_anomaly_store(anomaly_store_path) or {
            "rule_hit_events": [], "all_detections": [], "metadata": {}
        }
        rule_hit_events = anomaly_store.get("rule_hit_events", [])
        print(f"[LLMRouter] Loaded {len(rule_hit_events)} rule-hit events "
              f"from {anomaly_store_path}")

        os.makedirs(output_dir, exist_ok=True)
        reports: List[dict] = []

        for narrative in scrubbed_narratives:
            campaign_id = narrative.get("campaign_id", "UNKNOWN")
            confidence  = narrative.get("confidence", 0.0)

            if confidence < floor:
                print(f"[LLMRouter] Skipping {campaign_id} "
                      f"(confidence {confidence:.3f} < {floor})")
                continue

            print(f"\n[LLMRouter] Processing {campaign_id} "
                  f"(severity={narrative.get('severity')}, confidence={confidence:.3f})")

            report = self._process_one(
                narrative, rule_hit_events, mappings, anomaly_store, output_dir
            )
            reports.append(report)

        print(f"\n[LLMRouter] Done — {len(reports)} reports generated.")
        return reports

    # ------------------------------------------------------------------ #
    # Internal
    # ------------------------------------------------------------------ #

    def _process_one(
        self,
        narrative:       dict,
        rule_hit_events: List[dict],
        mappings:        Dict[str, dict],
        anomaly_store:   dict,
        output_dir:      str,
    ) -> dict:
        campaign_id   = narrative.get("campaign_id", "UNKNOWN")
        mapping_entry = mappings.get(campaign_id, {})
        ph_map        = _build_placeholder_map(narrative, mapping_entry, rule_hit_events)

        # Step 1: Build prompt with full rule evidence
        messages = build_prompt_messages(narrative, rule_hit_events, ph_map)
        prompt_chars = sum(len(m["content"]) for m in messages)
        print(f"[LLMRouter]   Prompt size: {prompt_chars:,} chars "
              f"(~{prompt_chars // 4:,} tokens)")

        # Step 2: Call the in-house Gemma (complete_json parses + retries internally)
        t_start = time.time()
        analysis, api_stats, llm_status = _call_gemma(messages)
        api_stats["wall_time_s"] = round(time.time() - t_start, 2)
        parse_method = "complete_json"
        print(f"[LLMRouter]   Gemma {llm_status} in {api_stats['wall_time_s']}s "
              f"({api_stats.get('completion_tokens', '?')} completion tokens)")

        # Step 3: Validate sections
        analysis = _validate_sections(analysis, campaign_id, config.GEMMA_MODEL)

        # Step 5: Re-identify FULL analysis dict (covers attack_timeline,
        # anomaly_explanation entities, remediation actions — everywhere
        # placeholders might be embedded)
        if mapping_entry and llm_status != "failed":
            analysis = self._scrubber.reidentify_report(analysis, mapping_entry)
            print(f"[LLMRouter]   Re-identification applied "
                  f"({len(mapping_entry.get('reverse', {}))} tokens restored)")

        # Step 6: Assemble final report
        report = self._build_final_report(
            narrative      = narrative,
            analysis       = analysis,
            rule_hit_events= rule_hit_events,
            anomaly_store  = anomaly_store,
            api_stats      = api_stats,
            parse_method   = parse_method,
            llm_status     = llm_status,
            mapping_entry  = mapping_entry,
        )

        report_path = os.path.join(
            output_dir,
            f"final_incident_report_{campaign_id}.json",
        )
        self._save_report(report, report_path)
        return report

    def _build_final_report(
        self,
        narrative:       dict,
        analysis:        dict,
        rule_hit_events: List[dict],
        anomaly_store:   dict,
        api_stats:       dict,
        parse_method:    str,
        llm_status:      str,
        mapping_entry:   dict = None,
    ) -> dict:
        """Assemble the final analyst-facing report with the new schema."""
        # Re-identify campaign context fields (entry_point may be placeholder)
        raw_ctx = {
            "campaign_id":            narrative.get("campaign_id"),
            "severity":               narrative.get("severity"),
            "confidence":             narrative.get("confidence"),
            "duration_minutes":       narrative.get("duration_minutes"),
            "first_seen":             narrative.get("first_seen"),
            "last_seen":              narrative.get("last_seen"),
            "entry_point":            narrative.get("entry_point"),
            "entity_count":           narrative.get("entity_count"),
            "kill_chain_coverage":    narrative.get("kill_chain_coverage"),
            "kill_chain_completeness":narrative.get("kill_chain_completeness"),
        }
        campaign_ctx = (
            self._scrubber.reidentify_report(raw_ctx, mapping_entry)
            if mapping_entry else raw_ctx
        )

        # IOCs from the scrubbed narrative — re-identify them
        sd = narrative.get("llm_context", {}).get("structured_data", {})
        raw_iocs = sd.get("iocs", narrative.get("iocs", {}))
        iocs = (
            self._scrubber.reidentify_report(raw_iocs, mapping_entry)
            if mapping_entry else raw_iocs
        )

        # Top-5 key evidence (already re-identified because rule_hit_events
        # were extracted from raw bundles BEFORE scrubbing)
        key_evidence = _build_key_evidence(rule_hit_events, top_n=5)

        # Per-event severity tier from rule score
        def _sev(score: float) -> str:
            if score >= 80: return "CRITICAL"
            if score >= 50: return "HIGH"
            if score >= 30: return "MEDIUM"
            return "LOW"

        # detected_anomalies — sorted by severity (CRITICAL first),
        # then by timestamp within each tier
        _SEV_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}

        annotated = []
        for ev in rule_hit_events:
            score   = float(ev.get("rule_score", 0))
            severity = _sev(score)
            annotated.append({
                "severity":           severity,
                "timestamp":          ev.get("timestamp"),
                "entity":             ev.get("entity"),
                "source_ip":          ev.get("source_ip"),
                "destination_ip":     ev.get("destination_ip"),
                "destination_port":   ev.get("destination_port"),
                "event_module":       ev.get("event_module"),
                "primary_rule":       ev.get("primary_rule"),
                "all_rules_fired":    ev.get("all_rules_fired"),
                "score":              score,
                "confidence":         ev.get("rule_confidence"),
                "mitre_technique_id": ev.get("mitre_technique_id"),
                "mitre_tactic":       ev.get("mitre_tactic"),
                "kill_chain_stage":   ev.get("kill_chain_stage"),
                "what_it_means":      ev.get("what_it_means"),
            })

        detected_anomalies = sorted(
            annotated,
            key=lambda a: (_SEV_ORDER[a["severity"]], a.get("timestamp", ""))
        )

        # Severity breakdown for quick analyst scan
        anomaly_severity_breakdown = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for a in detected_anomalies:
            anomaly_severity_breakdown[a["severity"]] += 1
        anomaly_severity_breakdown["TOTAL"] = len(detected_anomalies)

        # Detection summary stats
        store_meta    = anomaly_store.get("metadata", {})
        detection_stats = {
            "total_events_analysed":  store_meta.get("total_bundles", 0),
            "rule_hit_events":        store_meta.get("rule_hit_event_count", 0),
            "all_detection_events":   store_meta.get("all_detection_count", 0),
            "unique_rules_fired":     store_meta.get("unique_rules_fired", []),
            "rule_counts":            store_meta.get("rule_counts", {}),
            "stage_counts":           store_meta.get("stage_counts", {}),
        }

        return {
            "report_id": (
                f"RPT-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-"
                f"{narrative.get('campaign_id', 'UNKNOWN')}"
            ),
            "generated_at": datetime.now(timezone.utc).isoformat(),

            # ── Headline ──
            "executive_summary":   analysis.get("executive_summary",   {}),

            # ── Attack story ──
            "attack_timeline":     analysis.get("attack_timeline",     []),

            # ── Numerical verdict ──
            "risk_assessment":     analysis.get("risk_assessment",     {}),

            # ── Actionable fix ──
            "remediation":         analysis.get("remediation",         {}),

            # ── Top 5 plain-English signals ──
            "key_evidence":        key_evidence,

            # ── LLM analytical explanation ──
            "anomaly_explanation": analysis.get("anomaly_explanation", {}),

            # ── Severity distribution of detected anomalies ──
            "anomaly_severity_breakdown": anomaly_severity_breakdown,

            # ── Full detection record (every rule-hit event, sorted by severity) ──
            "detected_anomalies":  detected_anomalies,

            # ── Threat intel ──
            "iocs":                iocs,

            # ── Campaign metadata (non-LLM) ──
            "campaign_context":    campaign_ctx,

            # ── Detection stats ──
            "detection_stats":     detection_stats,

            # ── Processing audit trail ──
            "processing": {
                "llm_model":         config.GEMMA_MODEL,
                "api_endpoint":      config.GEMMA_BASE_URL,
                "llm_status":        llm_status,
                "json_parse_method": parse_method,
                "json_mode_used":    api_stats.get("json_mode_used", False),
                "prompt_tokens":     api_stats.get("prompt_tokens",     0),
                "completion_tokens": api_stats.get("completion_tokens", 0),
                "api_latency_ms":    api_stats.get("latency_ms",        0),
                "wall_time_s":       api_stats.get("wall_time_s",       0),
            },
        }

    @staticmethod
    def _save_report(report: dict, path: str):
        os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        size_kb = os.path.getsize(path) / 1024
        print(f"[LLMRouter]   Final report → {path}  ({size_kb:.1f} KB)")
